feat: add contentful webhook

diff --git a/.github/workflows/contentful.yml b/.github/workflows/contentful.yml
--- a/.github/workflows/contentful.yml
+++ b/.github/workflows/contentful.yml
@@ -1,31 +1,75 @@
-name: Eleventy Build on Contentful Publish Event
+name: Build on Contentful Publish Event
 on:
     repository_dispatch:
         types: [publish-event]
 
 jobs:
-    deploy:
+    # Build job
+    build:
         runs-on: ubuntu-latest
+        env:
+            CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
+            CONTENTFUL_ACCESS_KEY: ${{ secrets.CONTENTFUL_ACCESS_KEY }}
         steps:
-            - uses: actions/checkout@v2
+            - name: Checkout
+              uses: actions/checkout@v4
+            - name: Detect package manager
+              id: detect-package-manager
+              run: |
+                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                    echo "manager=yarn" >> $GITHUB_OUTPUT
+                    echo "command=install" >> $GITHUB_OUTPUT
+                    echo "runner=yarn" >> $GITHUB_OUTPUT
+                    exit 0
+                  elif [ -f "${{ github.workspace }}/package.json" ]; then
+                    echo "manager=npm" >> $GITHUB_OUTPUT
+                    echo "command=ci" >> $GITHUB_OUTPUT
+                    echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                    exit 0
+                  else
+                    echo "Unable to determine package manager"
+                    exit 1
+                  fi
             - name: Setup Node
-              uses: actions/setup-node@v1
+              uses: actions/setup-node@v4
               with:
-                  node-version: "12.x"
-
-            - name: Cache dependencies
-              uses: actions/cache@v1
+                  node-version: "20"
+                  cache: ${{ steps.detect-package-manager.outputs.manager }}
+            - name: Setup Pages
+              uses: actions/configure-pages@v5
               with:
-                  path: ~/.npm
-                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+                  # Automatically inject basePath in your Next.js configuration file and disable
+                  # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
+                  #
+                  # You may remove this line if you want to manage the configuration yourself.
+                  static_site_generator: next
+            - name: Restore cache
+              uses: actions/cache@v4
+              with:
+                  path: |
+                      .next/cache
+                  # Generate a new cache whenever packages or source files change.
+                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+                  # If source files changed but packages didn't, rebuild from a prior cache.
                   restore-keys: |
-                      ${{ runner.os }}-node-
-
-            - run: npm ci
-            - run: npm run build
-
-            - name: Deploy
-              uses: peaceiris/actions-gh-pages@v3
+                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+            - name: Install dependencies
+              run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+            - name: Build with Next.js
+              run: ${{ steps.detect-package-manager.outputs.runner }} next build
+            - name: Upload artifact
+              uses: actions/upload-pages-artifact@v3
               with:
-                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
-                  publish_dir: _site
+                  path: ./out
+
+    # Deployment job
+    deploy:
+        environment:
+            name: github-pages
+            url: ${{ steps.deployment.outputs.page_url }}
+        runs-on: ubuntu-latest
+        needs: build
+        steps:
+            - name: Deploy to GitHub Pages
+              id: deployment
+              uses: actions/deploy-pages@v4
